### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Kflash** [candeza/candeza#2]
Left to fix:

- [ ] Watch task
- [ ] Run tests in individual contexts (*CLI*)
- [ ] Finish CLI
- [ ] Finish plugin and preprocessors
- [ ] Better reporter layout

To better understand wich step of developing I'm here... If you want to give candeza a spin and play around, you can do so if you: 

```js
// install from npm
npm i candeza

// create a test file and to this:

var candeza = require('candeza');
// create a suite
var suite = candeza('My first test');

suite.test(function(t) {
   t.pass();
});

```

**Comment by Kflash** [comment]
For those who read this nonsense. Why not give candeza a try? It's not finished yet, but tested by a couple of companies so it's not so many bugs in the main core.

You can do so if you: 

```js
// install from npm
npm i candeza

// create a test file and to this:

var candeza = require('candeza');
// create a suite
var suite = candeza('My first test');

suite.test(function(t) {
   t.pass();
});

```
On the CMD just type `candeza` if your test are located inside the test folder.

It is very fast, agree? :+1:
